version: '3.4'

services:
  db:
    restart: always
    container_name: decide_db
    image: postgres:11.1-alpine

  web:
    restart: always
    container_name: decide_web
    image: decide_web:latest
    build: .
    command: ash -c "python manage.py migrate && gunicorn -w 5 decide.wsgi --timeout=500 -b 0.0.0.0:5000"
    expose:
      - "5000"
    volumes:
      - static:/app/static
    depends_on:
      - db

  nginx:
    restart: always
    container_name: decide_nginx
    image: decide_nginx:latest
    build:
        context: .
        dockerfile: Dockerfile-nginx
    volumes:
      - static:/app/static
    ports:
      - "80:80"
    depends_on:
      - web


volumes:
  static:
    name: decide_static
  db:
    name: decide_db


